"use client";
import {useEffect,useRef,useState} from 'react';import {useSession} from 'next-auth/react';import Link from 'next/link';
import {useLiveCommerce} from '@/hooks/use-live-commerce';import {formatMinor} from '@/lib/catalog-data';import {isOrder} from '@/lib/checkout-data';
import {createParcel,markParcelReady,requestRefund,cancelShipment,getShipmentDocument} from '@/lib/generated/commerce-client';
import type {OrderView,StaffOrderOperations} from '@/lib/generated/commerce-types';
const list=(v:unknown):v is OrderView[]=>Array.isArray(v)&&v.length<=50&&v.every(isOrder);
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object';
const integer=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
const operations=(v:unknown):v is StaffOrderOperations=>object(v)&&isOrder(v.order)
 &&Array.isArray(v.items)&&v.items.length<=50&&v.items.every(i=>object(i)&&typeof i.productId==='string'&&typeof i.name==='string'&&integer(i.quantity)&&i.quantity>=1&&integer(i.allocatedQuantity)&&i.allocatedQuantity<=i.quantity&&integer(i.totalMinor))
 &&Array.isArray(v.parcels)&&v.parcels.length<=100&&v.parcels.every(p=>object(p)&&typeof p.id==='string'&&typeof p.orderId==='string'&&typeof p.state==='string'&&integer(p.version))
 &&Array.isArray(v.refunds)&&v.refunds.length<=100&&v.refunds.every(r=>object(r)&&typeof r.id==='string'&&typeof r.orderId==='string'&&typeof r.state==='string'&&integer(r.amountMinor));
export function StaffOrderList(){const {data:session,status}=useSession();const live=useLiveCommerce('/api/commerce/staff/orders',list,status==='authenticated'?session.user.id:'',status==='authenticated');return <section className="max-w-5xl mx-auto px-4 py-10 space-y-5"><h1 className="text-3xl font-bold">Staff orders</h1><p>These operations require your assigned staff permissions.</p>{live.error&&<p role="alert">{live.error}</p>}{live.data?.map(o=><Link key={o.id} href={'/staff/orders/'+encodeURIComponent(o.id)} className="block border rounded-xl p-4">{o.id} · {formatMinor(o.totalMinor)} · {o.paymentState}</Link>)}</section>;}
export function StaffOperations({id}:{id:string}){
 const {data:session,status}=useSession();const identity=(status==='authenticated'?session.user.id:'')+':'+id;const active=useRef(identity);active.current=identity;
 const live=useLiveCommerce('/api/commerce/staff/orders/'+encodeURIComponent(id)+'/operations',operations,identity,status==='authenticated');
 const [busy,setBusy]=useState('');const [notice,setNotice]=useState<{identity:string;text:string}|null>(null);const [amount,setAmount]=useState('');const [reason,setReason]=useState('');
 const [measure,setMeasure]=useState({weightGrams:500,lengthMm:200,widthMm:150,heightMm:50});const [quantities,setQuantities]=useState<Record<string,number>>({});
 const retries=useRef<Record<string,{signature:string;key:string}>>({});
 useEffect(()=>{setAmount('');setReason('');setQuantities({});setBusy('');retries.current={};},[identity]);
 function key(kind:string,body:unknown){const signature=JSON.stringify({identity,body});const prior=retries.current[kind];if(prior?.signature===signature)return prior.key;const value={signature,key:crypto.randomUUID()};retries.current[kind]=value;return value.key;}
 async function act(action:()=>Promise<unknown>,success:string){if(busy===identity||live.error)return;setBusy(identity);setNotice(null);try{await action();if(active.current===identity){setNotice({identity,text:success});live.refresh();}}catch{if(active.current===identity){setNotice({identity,text:'The operation could not be confirmed. Review the latest status before retrying.'});live.refresh();}}finally{if(active.current===identity)setBusy('');}}
 const disabled=busy===identity||!!live.error;const data=live.data;
 return <section className="max-w-5xl mx-auto px-4 py-10 space-y-6"><Link href="/staff/orders" className="underline">Staff orders</Link><h1 className="text-3xl font-bold">Order operations</h1>{live.error&&<p role="alert">{live.error}</p>}{notice?.identity===identity&&<p role="status">{notice.text}</p>}{data&&<>
  <div className="border rounded-xl p-5"><p>{data.order.id}</p><p>{data.order.paymentState} · {data.order.fulfillmentState}</p><p>{formatMinor(data.order.totalMinor)}</p></div>
  <div className="border rounded-xl p-5 space-y-4"><h2 className="text-xl font-semibold">Pack a parcel</h2><p>Record actual measurements and the units in this parcel.</p>{data.items.map(item=><label key={item.productId} className="block">{item.name} ({item.quantity-item.allocatedQuantity} units remaining)<input aria-label={'Pack quantity for '+item.name} type="number" min={0} max={item.quantity-item.allocatedQuantity} value={quantities[item.productId]??item.quantity-item.allocatedQuantity} onChange={e=>setQuantities({...quantities,[item.productId]:Number(e.target.value)})} className="border rounded p-2 ml-4"/></label>)}
   <div className="flex flex-wrap gap-4">{(['weightGrams','lengthMm','widthMm','heightMm'] as const).map(k=><label key={k}>{k==='weightGrams'?'Weight (g)':k.replace('Mm','')+' (mm)'}<input type="number" min={1} max={k==='weightGrams'?30000:2000} value={measure[k]} onChange={e=>setMeasure({...measure,[k]:Number(e.target.value)})} className="block border rounded p-2"/></label>)}</div>
   <button disabled={disabled||data.order.paymentState!=='CAPTURED'} className="border rounded px-4 py-2 disabled:opacity-40" onClick={()=>void act(()=>{const body={...measure,items:data.items.map(i=>({productId:i.productId,quantity:quantities[i.productId]??i.quantity-i.allocatedQuantity})).filter(i=>i.quantity>0)};return createParcel(id,body,key('parcel',body));},'Parcel saved. Confirm packed-ready after checking its contents.')}>Save parcel</button>
   {data.parcels.map(p=><div key={p.id} className="border rounded p-4 space-y-2"><p>{p.id} · {p.state}</p>{p.state==='AWAITING_PACKING'&&<button disabled={disabled} className="underline" onClick={()=>void act(()=>markParcelReady(p.id,{version:p.version}),'Packed-ready confirmed. Shipping will be processed asynchronously.')}>Confirm packed-ready</button>}{['LABEL_READY','AWAITING_PICKUP'].includes(p.state)&&<><button disabled={disabled} className="underline mr-4" onClick={()=>void act(async()=>{const result=await getShipmentDocument(p.id);const url=new URL(result.url);if(url.protocol!=='https:')throw Error('Invalid document');if(active.current===identity)window.open(url.toString(),'_blank','noopener,noreferrer');},'Label link opened.')}>Open private label</button><button disabled={disabled||!reason.trim()} className="underline" onClick={()=>void act(()=>cancelShipment(p.id,{version:p.version,reason}),'Carrier cancellation requested. This does not refund the customer.')}>Request carrier cancellation</button></>}</div>)}
  </div>
  <div className="border rounded-xl p-5 space-y-4"><h2 className="text-xl font-semibold">Refund review</h2><p>Refunds and physical shipment cancellation are separate actions.</p><label className="block">Reason<input value={reason} maxLength={240} onChange={e=>setReason(e.target.value)} className="block border rounded p-2 w-full"/></label><label className="block">Refund amount (₹)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="block border rounded p-2"/></label>
   <button disabled={disabled||!reason.trim()||!/^\d+(\.\d{1,2})?$/.test(amount)||Number(amount)<=0} className="border rounded px-4 py-2 disabled:opacity-40" onClick={()=>void act(()=>{const body={amountMinor:Math.round(Number(amount)*100),reason};return requestRefund(id,body,key('refund',body));},'Refund request saved. Track its provider confirmation below.')}>Request approved refund</button>
   {data.refunds.map(r=><p key={r.id}>{r.id} · {formatMinor(r.amountMinor)} · {r.state}</p>)}
  </div>
 </>}</section>;
}
