import {test,expect,Page} from '@playwright/test';
async function fixtures(page:Page){
 const state={price:20000,version:0,quantity:3,orders:0,quoteId:'quote-fixture',key:'',conflict:false,paymentReady:false,parcel:false,packed:false,refund:false,emailOn:false,smsOn:false,prefVersion:0};
 await page.route('https://checkout.razorpay.com/**',route=>route.fulfill({contentType:'text/javascript',body:'window.Razorpay=class { constructor(options){window.fixturePayment=options;} open(){window.fixturePaymentOpened=true;} };'}));
 await page.route('**/api/auth/providers',route=>route.fulfill({json:{cognito:{id:'cognito',name:'Cognito',type:'oauth',signinUrl:'http://127.0.0.1:3002/api/auth/signin/cognito',callbackUrl:'http://127.0.0.1:3002/api/auth/callback/cognito'}}}));
 await page.route('**/api/auth/session',route=>route.fulfill({json:{user:{id:'alice-fixture',name:'Fixture Customer',email:'customer@example.test',role:'CUSTOMER'},expires:'2099-01-01T00:00:00Z'}}));
 const product=()=>({id:'p1',name:'Fixture Pads',sku:'fixture-sku',slug:'fixture-pads',description:'Fixture product',image:'/products/wellisha-hero.jpg',currency:'INR',categoryId:null,priceMinor:state.price,basePriceMinor:state.price,discountMinor:0,offerTitle:null,offerSummary:null,priceVersion:state.version,available:true});
 await page.route('**/api/catalog**',route=>{const url=new URL(route.request().url());return route.fulfill({json:url.pathname.endsWith('categories')?[]:url.pathname==='/api/catalog'?{items:[product()],page:0,hasMore:false,pricedAt:new Date().toISOString(),refreshAfterMs:1000}:{product:product(),variants:[{id:'p1',slug:'fixture-pads',label:'Regular',priceMinor:state.price,available:true}],bundleContents:[{productId:'p2',name:'Fixture Liners',quantity:2}],pricedAt:new Date().toISOString(),refreshAfterMs:1000}});});
 await page.route('**/api/commerce/**',async route=>{
  const path=new URL(route.request().url()).pathname;const method=route.request().method();
  if(path.endsWith('/me/notification-preferences')){if(method==='PATCH'){const body=route.request().postDataJSON();state.emailOn=body.emailEnabled;state.smsOn=body.smsEnabled;state.prefVersion++;}return route.fulfill({json:{emailEnabled:state.emailOn,smsEnabled:state.smsOn,version:state.prefVersion}});}
  if(path.endsWith('/staff/orders/o1/operations'))return route.fulfill({json:{order:{id:'o1',totalMinor:60000,currency:'INR',paymentState:'CAPTURED',fulfillmentState:'AWAITING_PACKING',createdAt:new Date().toISOString()},items:[{productId:'p1',name:'Fixture Pads',quantity:3,totalMinor:60000,allocatedQuantity:state.parcel?3:0}],parcels:state.parcel?[{id:'s1',orderId:'o1',state:state.packed?'PACKED_READY':'AWAITING_PACKING',version:state.packed?1:0}]:[],refunds:state.refund?[{id:'r1',orderId:'o1',amountMinor:100,state:'PENDING'}]:[]}});
  if(path.endsWith('/staff/orders/o1/packages')){expect(route.request().postDataJSON().items).toEqual([{productId:'p1',quantity:3}]);state.parcel=true;return route.fulfill({status:201,json:{id:'s1',orderId:'o1',state:'AWAITING_PACKING',version:0}});}
  if(path.endsWith('/staff/packages/s1/ready')){expect(route.request().postDataJSON()).toEqual({version:0});state.packed=true;return route.fulfill({status:202,json:{id:'s1',orderId:'o1',state:'PACKED_READY',version:1}});}
  if(path.endsWith('/staff/orders/o1/refunds')){expect(route.request().postDataJSON()).toEqual({amountMinor:100,reason:'Approved adjustment'});state.refund=true;return route.fulfill({status:202,json:{id:'r1',orderId:'o1',amountMinor:100,state:'PENDING'}});}
  if(path.endsWith('/cart'))return route.fulfill({json:{items:[{id:'c1',product:product(),quantity:state.quantity,lineTotalMinor:state.price*state.quantity,lineDiscountMinor:0,purchasable:true}],subtotalMinor:state.price*state.quantity,savingsMinor:0,currency:'INR',pricedAt:new Date().toISOString(),refreshAfterMs:1000}});
  if(path.endsWith('/cart/items/c1')){state.quantity=route.request().postDataJSON()?.quantity??state.quantity;return route.fulfill({status:204});}
  if(path.endsWith('/me/addresses'))return route.fulfill({json:[{id:'a1',name:'Fixture Customer',phone:'9999999999',addressLine:'Fixture Road',city:'Mumbai',state:'MH',pincode:'400001',version:0}]});
  if(path.endsWith('/checkout/quotes'))return route.fulfill({status:201,json:{id:state.quoteId,addressId:'a1',items:[{productId:'p1',quantity:state.quantity,basePriceMinor:state.price,discountMinor:0,totalMinor:state.price*state.quantity,priceVersion:state.version}],subtotalMinor:state.price*state.quantity,shippingMinor:0,totalMinor:state.price*state.quantity,currency:'INR',expiresAt:new Date(Date.now()+300000).toISOString()}});
  if(path==='/api/commerce/orders'&&method==='POST'){const body=route.request().postDataJSON();expect(body).toEqual({quoteId:state.quoteId});const key=route.request().headers()['idempotency-key'];expect(key).toBeTruthy();state.key=key;if(state.conflict)return route.fulfill({status:409,json:{code:'STATE_CONFLICT'}});state.orders++;return route.fulfill({status:202,json:{id:'o1',totalMinor:60000,currency:'INR',paymentState:state.paymentReady?'PAYMENT_READY':'PAYMENT_SETUP_PENDING',fulfillmentState:'AWAITING_PAYMENT',createdAt:new Date().toISOString()}});}
  if(path.endsWith('/orders/o1/payment'))return route.fulfill({json:{orderId:'o1',providerOrderId:'order_fixture',keyId:'rzp_test_fixture',amountMinor:60000,currency:'INR'}});
  if(path.endsWith('/orders/o1'))return route.fulfill({json:{id:'o1',totalMinor:60000,currency:'INR',paymentState:state.paymentReady?'PAYMENT_READY':'PAYMENT_SETUP_PENDING',fulfillmentState:'AWAITING_PAYMENT',createdAt:new Date().toISOString()}});
  return route.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND'}});
 });return state;
}
test('open catalog refreshes API prices without navigation',async({page})=>{const state=await fixtures(page);await page.goto('/products');await expect(page.getByText('Fixture Pads')).toBeVisible();await expect(page.getByText('₹200.00').first()).toBeVisible();state.price=17000;state.version++;await expect(page.getByText('₹170.00').first()).toBeVisible();await expect(page).toHaveURL(/\/products$/);});
test('cart reprices automatically while preserving quantity',async({page})=>{const state=await fixtures(page);await page.goto('/cart');await expect(page.getByText('₹600.00').first()).toBeVisible();state.price=17000;state.version++;await expect(page.getByText('₹510.00').first()).toBeVisible();await expect(page.getByRole('article').getByText('3',{exact:true})).toBeVisible();expect(state.quantity).toBe(3);});
test('quote requires confirmation and reload recovers the same owned order',async({page})=>{const state=await fixtures(page);await page.goto('/checkout');await page.getByLabel('Delivery address').selectOption('a1');await page.getByRole('button',{name:'Review current prices'}).click();await expect(page.getByText('Total: ₹600.00')).toBeVisible();expect(state.orders).toBe(0);await page.getByRole('button',{name:'Confirm this total'}).click();await expect(page.getByText('Order reference: o1')).toBeVisible();await page.reload();await expect(page.getByText('Order reference: o1')).toBeVisible();expect(state.orders).toBe(1);});
test('changed quote forces a fresh customer review',async({page})=>{const state=await fixtures(page);state.conflict=true;await page.goto('/checkout');await page.getByLabel('Delivery address').selectOption('a1');await page.getByRole('button',{name:'Review current prices'}).click();await page.getByRole('button',{name:'Confirm this total'}).click();await expect(page.getByText('The quote expired or prices, address or stock changed. Review a new quote.')).toBeVisible();expect(state.orders).toBe(0);await expect(page.getByRole('button',{name:'Confirm this total'})).toHaveCount(0);});
test('commerce sign-in and signup show the configured secure account flow',async({page})=>{await fixtures(page);await page.goto('/login');await expect(page.getByRole('button',{name:'Continue to secure sign-in'})).toBeEnabled();await expect(page.getByText('Continue with Google')).toHaveCount(0);await page.goto('/register');await expect(page.getByRole('heading',{name:'Create your Wellisha account'})).toBeVisible();await expect(page.getByRole('button',{name:'Continue to secure sign-in'})).toBeEnabled();});
test('staff packs a parcel and reviews a bounded refund',async({page})=>{const state=await fixtures(page);await page.goto('/staff/orders/o1');await expect(page.getByRole('heading',{name:'Order operations'})).toBeVisible();await page.getByRole('button',{name:'Save parcel'}).click();await page.getByRole('button',{name:'Confirm packed-ready'}).click();await expect(page.getByText('s1 · PACKED_READY')).toBeVisible();await page.getByLabel('Reason',{exact:true}).fill('Approved adjustment');await page.getByLabel('Refund amount (₹)').fill('1.00');await page.getByRole('button',{name:'Request approved refund'}).click();await expect(page.getByText('r1 · ₹1.00 · PENDING')).toBeVisible();expect(state.packed).toBe(true);expect(state.refund).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/staff-operations.png',fullPage:true});});
test('customer opts into verified-contact notifications',async({page})=>{const state=await fixtures(page);await page.goto('/account/notification-settings');await page.getByLabel('Email',{exact:true}).click();await expect(page.getByLabel('Email',{exact:true})).toBeChecked();expect(state.emailOn).toBe(true);await expect(page.getByLabel('SMS',{exact:true})).not.toBeChecked();});
test('mobile checkout remains within the viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await fixtures(page);await page.goto('/checkout');await page.getByLabel('Delivery address').selectOption('a1');await page.getByRole('button',{name:'Review current prices'}).click();await expect(page.getByText('Total: ₹600.00')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'test-results/mobile-checkout.png',fullPage:true});});

test('product detail shows variant price and prepacked contents',async({page})=>{await fixtures(page);await page.goto('/products/fixture-pads');await expect(page.getByRole('heading',{name:'Fixture Pads'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Choose a variant'})).toBeVisible();await expect(page.getByText('2 × Fixture Liners')).toBeVisible();});
test('browser payment success cannot authorize fulfillment',async({page})=>{const state=await fixtures(page);state.paymentReady=true;await page.goto('/checkout');await page.getByLabel('Delivery address').selectOption('a1');await page.getByRole('button',{name:'Review current prices'}).click();await page.getByRole('button',{name:'Confirm this total'}).click();await page.getByRole('button',{name:'Pay securely'}).click();await page.evaluate(()=>{const windowFixture=window as unknown as {fixturePayment:{handler:()=>void}};windowFixture.fixturePayment.handler();});await expect(page.getByText('Payment submitted. Waiting for verified confirmation.')).toBeVisible();await expect(page.getByText('Payment: payment ready')).toBeVisible();expect(state.orders).toBe(1);});
